POST http://localhost:5000/user/createuser
Content-Type: application/json

{
    "username":"Ravi",
    "password":"ravi",
    "email":"ravi@mail.com",
    "city":"Kerala",
    "age":28
}

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username":"Ravi",
    "password":"ravi"
}

###
POST http://localhost:5000/admin/createadmin
Content-Type: application/json

{
    "username":"Raju",
    "password":"raju"
}

###
POST http://localhost:5000/admin/addmovie
Content-Type: application/json

{
    "username":"Raju",
    "movieList":[
        {
            "movieName":"Harry Potter",
            "genre":"Thriller",
            "rating":"4",
            "duration": "1h 15m",
            "year":2000,
            "status":false,
            "language":"English",
            "description":"Throughout the series, Harry is described as having his father's perpetually untidy black hair, his mother's bright green eyes, and a lightning bolt-shaped scar on his forehead. He is further described as 'small and skinny for his age' with 'a thin face' and 'knobbly knees, and he wears Windsor glasses."
        }
    ]
}

###
GET http://localhost:5000/admin/getmovies


###
GET http://localhost:5000/admin/getmovie/The Conjuring

###
PUT http://localhost:5000/admin/removemovie
Content-Type: application/json

{
    "movieName":"FIR"
}







###
POST http://localhost:5000/admin/login
Content-Type: application/json

{
    "username":"Raju",
    "password":"raju"
}








###
POST http://localhost:5000/seat/createseat
Content-Type: application/json

{
    "seatNumber":"A5"

}

###
GET http://localhost:5000/seat/getseat/A1

###
GET http://localhost:5000/seat/getallseats


###
PUT http://localhost:5000/seat/updateseat
Content-Type: application/json

{
    "seatNumber":"A2",
    "isSeatSelected":false,
    "isSeatBooked":false

}